version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student
      MYSQL_USER: temp
      MYSQL_PASSWORD: temp
    ports:
      - 9906:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db

  php-apache-environment:
    container_name: php-apache
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
        - db
    volumes:
        - .:/var/www/html/
    ports:
        - 8000:80




# version: '3.1'
# services:
#   db:
#     image: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: test_db
#     ports:
#       - "3308:3306"
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     restart: always
#     environment:
#       PMA_HOST: db
#       PMA_USER: root
#       PMA_PASSWORD: root
#     ports:
#       - "8080:80"



# version: "3.8"
# services:
#   backend:
#     image: golang:1.19.1-alpine
#     tty: true
#     ports:
#       - 4000:4000
#     volumes:
#       - .:/go/project
#     depends_on:
#       - db

#   db:
#     image: mysql:5.7.22
#     restart: always
#     environment:
#       MYSQL_DATABASE: bookstore
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#       MYSQL_ROOT_PASSWORD: root
#     volumes:
#       - .dbdata:/var/lib/mysql
#     ports:
#       - 3306:3306
